# Generated by Django 3.1.2 on 2020-10-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201017_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='snippet', max_length=250, verbose_name='snippet'),
            preserve_default=False,
        ),
    ]
