# Generated by Django 3.1.2 on 2020-10-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
