# Generated by Django 3.1.2 on 2020-10-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201017_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(),
        ),
    ]
