# Generated by Django 3.1.2 on 2020-10-17 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201017_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published_date2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
