# Generated by Django 3.1.2 on 2020-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201017_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='modified_date2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
